amp: false
batch_size: 16
bert: homersimpson/subsec-xlm-roberta-portuguese-30k
bert_pad_index: null
bert_pooling: mean
binarize: false
bos_index: 0
buckets: 32
build: false
cache: false
char_pad_index: null
checkpoint: false
clip: 5.0
dev: gl_ctg-ud-dev.conllu
device: '0'
dist: ddp
embed: glove-6b-100
encoder: bert
encoder_dropout: 0.1
epochs: 4
even: false
feat: null
fix_len: 20
local_rank: 0
lr: 2.0e-05
lr_rate: 20
max_len: null
min_freq: 2
mix_dropout: 0.0
mlp_dropout: 0.33
mode: train
n_arc_mlp: 500
n_bert_layers: 4
n_chars: null
n_rel_mlp: 100
n_rels: 29
n_tags: null
n_words: 30000
pad_index: 1
partial: false
path: dep/gal/pt/model
patience: 100
proj: false
punct: false
seed: 86
steps: 9080
test: gl_ctg-ud-test.conllu
threads: 16
train: gl_ctg-ud-train.conllu
tree: false
unk_index: 3
update_steps: 1
verbose: true
wandb: false
warmup: 0.1
workers: 0
